#!/bin/sh

set -u

: "${IBUS_FAKE_STATE:?IBUS_FAKE_STATE is required}"

case ${1:-} in
    engine)
        if [ -n "${IBUS_FAKE_READY_FILE:-}" ] && [ ! -f "$IBUS_FAKE_READY_FILE" ]; then
            exit 1
        fi
        if [ "$#" -eq 1 ]; then
            sed -n '1p' "$IBUS_FAKE_STATE"
        else
            printf '%s\n' "$2" > "$IBUS_FAKE_STATE"
            if [ -n "${IBUS_FAKE_SWITCH_EXIT:-}" ]; then
                exit "$IBUS_FAKE_SWITCH_EXIT"
            fi
        fi
        ;;
    list-engine)
        printf '%s\n' 'xkb:us::eng' 'mozc-jp' 'mozc-on'
        ;;
    address)
        printf '%s\n' 'unix:path=/tmp/fake-ibus'
        ;;
    *)
        printf 'unexpected fake ibus command: %s\n' "$*" >&2
        exit 2
        ;;
esac
